// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:8054d68d-418d-4107-9781-75158b163776",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_vu6TKyK6G",
    "aws_user_pools_web_client_id": "2c28lg7ja8nlb4g9olgct6cle",
    "aws_mobile_analytics_app_id": "d014bb9ae1af4724a6697a0f444a8719",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "amplifyjsapp-20181212110542-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://amplifyjsapp-20181212110542-hostingbucket.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
